baseURL = 'https://bleedkagax.github.io/'
languageCode = 'en-us'
title = 'Kaga Blog'
theme = 'beautifulhugo'
[module]
  [[module.imports]]
    path = "github.com/hugomods/mermaid"
  [[module.imports]]
    path = "github.com/halogenica/beautifulhugo"    
[params]
  [params.mermaid]
    js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'






